module.exports = {
  TEST_STARTED: 'TEST_STARTED',
  TEST_SUBMITTED: 'TEST_SUBMITTED',
  SCORE_UPDATED: 'SCORE_UPDATED',
  STREAK_UPDATED: 'STREAK_UPDATED',
  XP_UPDATED: 'XP_UPDATED',
  QUESTION_ATTEMPTED: 'QUESTION_ATTEMPTED',
  ATTEMPT_COMPLETED: 'ATTEMPT_COMPLETED',
  LEARNING_PROGRESS_UPDATED: 'LEARNING_PROGRESS_UPDATED',
  ATTEMPT_SUBMITTED: 'ATTEMPT_SUBMITTED',
  CONTENT_VIEWED: 'CONTENT_VIEWED',
  SKILL_UPDATED: 'SKILL_UPDATED',
};
